export const data = [
  {
    id: 9,
    author: "Bonnie Schulkin",
    durationStart: "12.2020",
    durationEnd: "12.2020",
    platform: "Udemy",
    courses: ["React testing with Jest and enzyme"],
  },
  {
    id: 8,
    author: "Dmytro Danylov",
    durationStart: "12.2020",
    durationEnd: "12.2020",
    platform: "Udemy",
    courses: ["Using typescript with react"],
  },
  {
    id: 7,
    author: "-",
    durationStart: "10.2020",
    durationEnd: "12.2020",
    platform: "github",
    courses: ["Code review"],
  },
  {
    id: 6,
    author: "Bonnie Schulkin",
    durationStart: "10.2020",
    durationEnd: "10.2020",
    platform: "Udemy",
    courses: ["React testing with Jest and enzyme"],
  },
  {
    id: 5,
    author: "Reed Barger,eduweb.pl,Jarosław Łojko",
    durationStart: "09.2020",
    durationEnd: "09.2020",
    platform: "Udemy",
    courses: ["React Hooks", "GIT", "Podstawy Scrum i Agile"],
  },
  {
    id: 4,
    author: "Daniel Siwek",
    durationStart: "05.2020",
    durationEnd: "09.2020",
    platform: "Udemy",
    courses: ["Kurs React dla średnio-zaawansowanych"],
  },
  {
    id: 3,
    author: "Bartłomiej Borowczyk",
    durationStart: "02.2020",
    durationEnd: "05.2020",
    platform: "Udemy",
    courses: [
      "Programowanie w JS",
      "React od podstaw",
      "Zaawansowane projekty w CSS i JavaScript",
      "Wprowadzenie do git i github",
    ],
  },
  {
    id: 2,
    author: "Drew Ryan",
    durationStart: "01.2020",
    durationEnd: "02.2020",
    platform: "Udemy",
    courses: ["Bootstrap 4"],
  },
  {
    id: 1,
    author: "Mirosław Zelent",
    durationStart: "07.2019",
    durationEnd: "01.2020",
    platform: "Youtube",
    courses: [
      "C++",
      "Obiektowy C++",
      "HTML",
      "CSS",
      "PHP",
      "MySQL",
      "Bootstrap",
    ],
  },
];
